name: Update

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SSH_CON: root@n1zes.tk
  SSH_FOLDER: github-next-app/
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup ssh agent
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo "Host *
          StrictHostKeyChecking no" > ~/.ssh/config
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/config

    - name: Send files
      run: |
        ssh $SSH_CON "mkdir -p $SSH_FOLDER"
        tar czf - {.,}* | ssh $SSH_CON "cd $SSH_FOLDER/ && tar xvzf -"

    - name: Starting docker container
      run: |
        ssh $SSH_CON "
          cd $SSH_FOLDER
          sudo chmod -R 777 .
          docker-compose exec -T nodejs bash -c "npm run build"
          docker-compose down
          docker-compose up -d
        "